package fr.formation.inti.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer")
public class Customer implements java.io.Serializable {

	private Integer custId;
	private String address;
	private String city;
	private String custTypeCd;
	private String fedId;
	private String postalCode;
	private String state;


	public Customer() {
	}

	public Customer(String custTypeCd, String fedId) {
		this.custTypeCd = custTypeCd;
		this.fedId = fedId;
	}

	public Customer(String address, String city, String custTypeCd, String fedId, String postalCode, String state) {
		this.address = address;
		this.city = city;
		this.custTypeCd = custTypeCd;
		this.fedId = fedId;
		this.postalCode = postalCode;
		this.state = state;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CUST_ID", unique = true, nullable = false)
	public Integer getCustId() {
		return this.custId;
	}

	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	@Column(name = "ADDRESS", length = 30)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "CUST_TYPE_CD", nullable = false, length = 1)
	public String getCustTypeCd() {
		return this.custTypeCd;
	}

	public void setCustTypeCd(String custTypeCd) {
		this.custTypeCd = custTypeCd;
	}

	@Column(name = "FED_ID", nullable = false, length = 12)
	public String getFedId() {
		return this.fedId;
	}

	public void setFedId(String fedId) {
		this.fedId = fedId;
	}

	@Column(name = "POSTAL_CODE", length = 10)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "STATE", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}



}
